### ISSUE TITLE
Incorrect Link -> Enable VMWare Engine API access and node quota

### ISSUE THREAD

**Issue by hashbangbinbash** [NetAppDocs/netapp-solutions#171]
Page: [Deploy and configure the Virtualization Environment on Google Cloud Platform (GCP)](https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp-setup.html)

Link instead points to data replication task
https://docs.netapp.com/us-en/occm/task_replicating_data.html#data-replication-requirements

Should it be this link instead? -> https://cloud.google.com/vmware-engine/docs/quickstart-prerequisites

**Comment by kevin-hoke** [comment]
New source page: https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp/gcp-setup.html#deploy

I will have our solution TME have a look and comment on this.

**Comment by kevin-hoke** [comment]
Verified with the solution architect that the link used is the correct link
