### ISSUE TITLE
Incorrect link at the end of the page? 

### ISSUE THREAD

**Issue by hashbangbinbash** [NetAppDocs/netapp-solutions#172]
Page: [Deploy and configure the Virtualization Environment on Google Cloud Platform (GCP)](https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp-setup.html)

Where it states "For connecting from an on-premises network to VMware Engine private cloud, leverage cloud VPN or Cloud Interconnect for appropriate connectivity and make sure the required ports are open. For detailed steps, follow this link." 
The link takes me to an article on setting up iSCSI on Ubuntu -> https://ubuntu.com/server/docs/service-iscsi

**Comment by kevin-hoke** [comment]
New source page: https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp/gcp-setup.html#deploy

I will have our solution TME have a look and comment on this.

**Comment by kevin-hoke** [comment]
Verified with the solution architect that this is the correct link.
