### ISSUE TITLE
Link is not working 

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/netapp-solutions#177]
Page: [Get Started With NetApp 

Hello team.

The URL: https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html is not working in the section "Build Your Virtualized Data Fabric" in the option called: "VMware vSphere with ONTAP : NetApp Solutions".

Many thanks for checking this.

**Comment by kevin-hoke** [comment]
Thank you for your feedback and finding this issue.  It has been corrected and should be available for your review now.  Please let me know if there are any additional concerns or issues.

**Comment by jsuarezs** [comment]
Many thanks for correcting it.
