### ISSUE TITLE
Broken link for NetApp XCP File Analytics on left nav

### ISSUE THREAD

**Issue by baronnetwork** [NetAppDocs/netapp-solutions#182]
Page: [Migration workflow](https://docs.netapp.com/us-en/netapp-solutions/xcp/xcp-bp-migration-workflow-overview.html)

On the left hand nav of the Documentation for NetApp XCP, File Analytics links to https://docs.netapp.com/us-en/netapp-solutions/x which is a **broken** link.  Please update to the proper link which details XCP's file analytics capabilities. 

Thanks,

Hadrian

**Comment by kevin-hoke** [comment]
Thank your for your feedback.  The issue has been fixed and should be available now for your review.

**Comment by kevin-hoke** [comment]
Link has been fixed is now working.
