### ISSUE TITLE
Request for sample code in the ai document

### ISSUE THREAD

**Issue by sakaia** [NetAppDocs/netapp-solutions#21]
I  have a request for sample code in the ai document.
If sample code assumes Trident, Please consider trident installation parameters. (for example pvc name is `basic`).
It would be helpful for first time running. Of course, I should check all `DEFINE PARAMETERS` in sample code

**Comment by mboglesby** [comment]
@sakaia - The pvc named 'basic' that is mentioned in the Trident installation documentation is just an example. In a production cluster, you would generally want to give your pvc a descriptive name that reflects its intended use. Examples: 'mysql-db' (for a MySQL database PVC), 'ai-training-data' (for AI training data).

**Comment by sakaia** [comment]
Thank you for your description.
At this moment, I understand these parameters. but it is helpful to consider these connectivity in the document..

I close this issue.
