### ISSUE TITLE
This Item appears to be obsolete

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/netapp-solutions#212]
Page: [Data fabric powered by NetApp for big data architecture](https://docs.netapp.com/us-en/netapp-solutions/data-analytics/hdcs-sh-data-fabric-powered-by-netapp-for-big-data-architecture.html)

The NetApp NFS Direct Access component in this document is no longer available.  The GitHub site for it points out that it is obsolete (https://github.com/NetApp/NetApp-Hadoop-NFS-Connector).  The KB article about the download link not being available points to a ng- email address that is no longer valid. (https://kb.netapp.com/Advice_and_Troubleshooting%2FMiscellaneous%2FNetApp_FAS_NFS_Connector_download_link_not_found)

**Comment by kevin-hoke** [comment]
@mboglesby - can you or someone on the team please have a look at this.

**Comment by kevin-hoke** [comment]
@mboglesby - can we resolve this so the issue can be closed?

**Comment by mboglesby** [comment]
@kevin-hoke - I connected @DrKeno with Karthik (who owns this solution) via email to discuss this, but I'm not sure what came of that.

@DrKeno - Did you and Karthik resolve this? Can we mark this issue as resolved?

**Comment by DrKeno** [comment]
Hi Guys!  It's Ken Jeras ***@***.***)  - it seems awkward to refer to "NetApp NFS Direct Access" as if is a specific component from NetApp. To me, the diagram should just show the Spark Cluster accessing the ONTAP system via NFS without going through a block titled "NetApp NFS Direct Access".  However, since this diagram has been updated to remove the reference to the Hadoop NFS Connector which is what triggered this item to be opened, I'm good with closing this item as being resolved.


Ken
=============================

From: Michael Oglesby ***@***.***>
Date: Tuesday, August 2, 2022 at 10:27 AM
To: NetAppDocs/netapp-solutions ***@***.***>
Cc: Jeras, Ken ***@***.***>, Mention ***@***.***>
Subject: Re: [NetAppDocs/netapp-solutions] This Item appears to be obsolete (Issue #212)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



@kevin-hoke<https://github.com/kevin-hoke> - I connected @DrKeno<https://github.com/DrKeno> with Karthik (who owns this solution) via email to discuss this, but I'm not sure what came of that.

@DrKeno<https://github.com/DrKeno> - Did you and Karthik resolve this? Can we mark this issue as resolved?

**Comment by mboglesby** [comment]
Thanks for the follow-up, Ken!
