### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by josevtome** [NetAppDocs/netapp-solutions#214]
Page: [Get Started With NetApp & VMware]

There are several broken links below the "Explore video demonstrations of the latest VMware solutions" section. Some of those refer to resources from Insight. They show a warning and then end up in a 404 error. Checked with other colleagues and all got to the same error.

I was first interested in opening "Provisioning and Managing FlexGroup Datastores with ONTAP Tools"but it wa broken, and then noticed some other links broken in that page. I was planning on sending that link to a customer, I had to browse for an alternative in FieldPortal.

**Comment by josevtome** [comment]
Link to site in question: https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html#learn-about-netapp-and-vmware-solutions

**Comment by josevtome** [comment]
Link that seems broken: https://live.insight.netapp.com/detail/video/6211809869001/provisioning-and-managing-flexgroup-datastores-with-ontap-tools.mp4

**Comment by kevin-hoke** [comment]
Thank you for the feedback @josevtome.  With the Insight content moving from the provider for the Insight conference, we are in the process of getting the content moved to NetApp TV.  In the meantime, the videos that are not yet moved over have been disabled from the page.

**Comment by kevin-hoke** [comment]
Closing as available content has modified links and unavailable content has been removed.
