### ISSUE TITLE
Red Underline on image

### ISSUE THREAD

**Issue by Grantglass** [NetAppDocs/netapp-solutions#221]
Page: [TR-4928: Responsible AI and confidential inferencing - NetApp AI with Protopia Image Transformation](https://docs.netapp.com/us-en/netapp-solutions/ai/ai-protopia-overview.html)

If you look at the image, you will notice that "DataOps" has a red underline to it. This is distracting to the user, I would suggest adding DataOps to your dictionary, so it no longer shows up with a red underline on it.

**Comment by kevin-hoke** [comment]
@mboglesby - can you have a look at this and replace the necessary image without the "spell check" warning for DataOps?

**Comment by mboglesby** [comment]
This has been fixed.
