### ISSUE TITLE
Fix link title

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/netapp-solutions#234]
Page: [NetApp Solutions](https://docs.netapp.com/us-en/netapp-solutions/index.html)

Hi, just an easy one, in the Solution Landing Pages tile, "SAP HANA" is misspelled to "SAP HAHA".

Regards,
Gabi

**Comment by kevin-hoke** [comment]
Hi Gabi,

Thanks for the feedback.  This should be fixed now!
