### ISSUE TITLE
Not seeing the GCP related info in here

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/netapp-solutions#239]
Page: [Region Availability for NFS datastores on AWS / VMC, Azure / AVS, and GCP / GCVE](https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-regions.html)

Hi, the title explains about availability in the GCP side too but there is no info displayed.
Could we add the GCP related info or modify the title?

Regards,
Gabriel

**Comment by kevin-hoke** [comment]
@gabrieltokyo - This is a temporary situation as we await an announcement from Google on their public preview or GA plans.  The GCP content is drafted, but hidden as we await the announcement.

Would you prefer we: (1) leave it as is, or (2) remove the reference to the naming until the announcements are available?

**Comment by gabrieltokyo** [comment]
Difficult decission...
Could we leave it as is but add some sort of text like "coming soon" or "data will be populated after Google announcement"?

If it does not make sense, then I will choose (1).
(Better to have more people asking than think we don't consider at all)

Regards,
Gabriel

**Comment by kevin-hoke** [comment]
I've added text that the GCP content will be coming soon.  If you are okay with that, can you please close this issue?

**Comment by gabrieltokyo** [comment]
That's better for the time being.

Thank you @kevin-hoke 
Regards
