### ISSUE TITLE
Request for ai sample code 

### ISSUE THREAD

**Issue by sakaia** [NetAppDocs/netapp-solutions#24]
I hope sample code should contain at least MNIST or ResNet.

Please remove `No xxxxx` message.

```
data_prep_step_command = ["echo", "'No data prep command entered'"] # Replace this echo command with the data prep command that you wish to execute
# Training step
train_step_command = ["echo", "'No training command entered'"] # Replace this echo command with the training command that you wish to execute
# Inference validation step
validate_step_command = ["echo", "'No inference validation command entered'"] # Replace this echo command with the e
```

https://github.com/NetAppDocs/netapp-solutions/blob/master/ai/aicp_implement_an_end-to-end_ai_training_workflow_with_built-in_traceability_and_versioning.adoc

**Comment by mboglesby** [comment]
@sakaia - These three steps in the sample code are meant to be placeholders, as indicated in the comments. It is expected that a customer will replace these placeholder steps with the specific data prep, training, and validation steps that they wish to execute as part of the workflow.

**Comment by sakaia** [comment]
Thank you for your description.

Anyway, the code works without changing?

**Comment by mboglesby** [comment]
@sakaia - Yes, the code should work without changing.
