### ISSUE TITLE
Confirming AVS Availability? 

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/netapp-solutions#260]
Page: [Region Availability – NFS datastore for ANF](https://docs.netapp.com/us-en/netapp-solutions/ehc/azure/azure-regions.html)

The above page says that AVS isn't available in US East 2, but is listed as supported on Azure's site, https://azure.microsoft.com/en-us/global-infrastructure/services/?products=netapp,azure-vmware&regions=all

Edit - Our page says the list was updated in June, but per Azure AVS was up and running in US East 2. 

Which site is authoritative on availability? 

Thanks!

**Comment by TheFalldog** [comment]
PS. Colleague beat me to the punch. Plz merge with issue #259

**Comment by kevin-hoke** [comment]
Closing as a duplicate of issue 259.
