### ISSUE TITLE
Link to original source?

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/netapp-solutions#263]
Page: [Disaster Recovery with ANF and JetStream](https://docs.netapp.com/us-en/netapp-solutions/ehc/azure/azure-native-dr-jetstream.html)

I'm assuming that the JetStream documentation that this page is copied from (https://www.jetstreamsoft.com/portal/jetstream-knowledge-base/disaster-recovery-with-azure-netapp-files-jetstream-dr-and-avs-azure-vmware-solution/) is the original. Is there approval to use JetStream's content? Can a link be added reflecting the original source?

**Comment by kevin-hoke** [comment]
@TheFalldog - actually, the NetApp documentation is the initial source and JetStream copied it from our content.  They wanted to show their usage in some of our integrations and we allowed them to do so.  I will check into them linking to our content, but our source is the original.
