### ISSUE TITLE
Updated Links

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/netapp-solutions#264]
Page: [Overview of ANF Datastore Solutions](https://docs.netapp.com/us-en/netapp-solutions/ehc/azure/azure-native-overview.html)

Under last section of the page, _Integrate Azure NetApp Files with Azure VMware Solution_, the link should direct to the ANF for datastores documentation, https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?tabs=azure-portal

The documentation currently linked is specific to guest mounting volumes.

**Comment by kevin-hoke** [comment]
@TheFalldog - good catch!  The link should be updated now.  If this is what you expect, can you please close out this issue?  Please let me know if there are any other concerns or questions.

**Comment by TheFalldog** [comment]
Looks good, thanks!
