### ISSUE TITLE
link misconfigured/misleading

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/netapp-solutions#287]
Page: [Introduction to automation for ONTAP and vSphere](https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_auto_introduction.html)
![image](https://user-images.githubusercontent.com/20595311/192102581-60c44949-55f8-4394-aeae-b1fdae3b1968.png)

Menu on the left: "Virtualization -> VMware Virtualization for ONTAP -> What's New with ONTAP...

The "What's New..." Link leads to "https://raw.githubusercontent.com/NetAppDocs/ontap-whatsnew/main/ontap98fo_vmware_virtualization.html" which is not found:
"404: Not Found"

**Comment by kevin-hoke** [comment]
This link has been corrected and available now.
