### ISSUE TITLE
Mention of private preview with Netapp for GCVE

### ISSUE THREAD

**Issue by maldu23** [NetAppDocs/netapp-solutions#312]
Page: [NetApp Capabilities for Google Cloud Platform GCVE](https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp/gcp-gcve.html)

The documentation here states that the Netapp for GCVE as a supplemental datastore is in private preview. It is my understanding that it is now in public preview and should be stated as such in the documentation.

**Comment by kevin-hoke** [comment]
@maldu23 - it is actually in Private GA and the customer list is tightly controlled by Google.  We will fix up these statements when it is generally available to everyone.

**Comment by kevin-hoke** [comment]
Documentation addresses the GA of CVS as a native datastore on GCVE.
