### ISSUE TITLE
The "What's new" link does not work...

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/netapp-solutions#321]
Page: [NetApp Solutions for Virtualization](https://docs.netapp.com/us-en/netapp-solutions/virtualization/index.html)

Getting Started / Best Practices
[NetApp and VMware: Getting Started](https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html)
[NetApp ONTAP Benefits for VMware vSphere Administrators](https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_admin_introduction.html)
[**What's New** with ONTAP for VMware vSphere](https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_whats_new.html)
[VMware vSphere with ONTAP Best Practices](https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html)

___________________________

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.

(https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_whats_new.html)

**Comment by kevin-hoke** [comment]
This issue has been fixed and available now.
