### ISSUE TITLE
[TR-4798]URL link is not exist  on airflow helm deployment.

### ISSUE THREAD

**Issue by sakaia** [NetAppDocs/netapp-solutions#33]
Since airflow package moves quickly, it causes this kind of URL link is broken.

On page 64 of TR4798 (Oct 2020),  `deployment instructions` goes to https://artifacthub.io/packages/helm/stable/airflow
But it does not exist with message `Sorry, the package you requested was not found.`

It seems following URL or something?
https://github.com/airflow-helm/charts/tree/main/charts/airflow

**Comment by mboglesby** [comment]
It looks like they moved it to a new repo. This is the new link: https://artifacthub.io/packages/helm/airflow-helm/airflow. We will fix this in the document.
