### ISSUE TITLE
[TR4798] redis.enabled flag for airflow

### ISSUE THREAD

**Issue by sakaia** [NetAppDocs/netapp-solutions#34]
About 64 page, `custom-values.yaml`

Because Kubernetes Executor does not need redis pod, it is better for writing this.

```
redis:
  enabled: false # true is required for Celery executors
```

https://github.com/airflow-helm/charts/blob/0f40ffe1c1a2949463ff9c59549b4fdf75391cd1/charts/airflow/values.yaml#L21

**Comment by mboglesby** [comment]
Thanks for the suggestion. We will update our example when we update the document.
