### ISSUE TITLE
Installation script incorrectly redirects output to /dev/null

### ISSUE THREAD

**Issue by mika9m** [NetAppDocs/netapp-solutions#359]
Page: [Getting Started with NetApp solution automation](https://docs.netapp.com/us-en/netapp-solutions/automation/getting-started.html)

Redirecting output of the apt-get, yum and pip install commands to /dev/null is unnecessary and hides potential issues.

Also there is probably no point in copy-pasting the commands to separate script, they could be copy-pasted directly to shell.

**Comment by kevin-hoke** [comment]
This issue has been addressed and is now available.
