### ISSUE TITLE
Type-O in document

### ISSUE THREAD

**Issue by rbaetz** [NetAppDocs/netapp-solutions#361]
Page: [NetApp Solutions for VMware in Hyperscalers](https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-hyperscalers.html)

NetApp Storage Options
NetApp storage can be utilized in several ways - either as **guess** (guest) connected or as a supplemental NFS datastore - within each of the 3 major hyperscalers.

**Comment by kevin-hoke** [comment]
This has been fixed in the current production repository.
