### ISSUE TITLE
Where is CVS-Performance as Supplemental NFS Datastore

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/netapp-solutions#364]
Page: [NetApp Storage options for Public Cloud Providers](https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-datastore-intro.html)

Hi, will appreciate if we could make available the document for CVS-P as supplemental NFS Datastore.

Regards,
Gabriel

**Comment by kevin-hoke** [comment]
@gabrieltokyo - thank you for the feedback.  The requested documentation is in process and should be released early next week.  I will provide an update to this issue once it is available.

**Comment by kevin-hoke** [comment]
@sureshthoppay - Is this something you have released?  Or planning to?

**Comment by sureshthoppay** [comment]
It was already available at

https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp/gcp-ncvs-datastore.html#overview
