### ISSUE TITLE
Define acronyms used in the documentation set.

### ISSUE THREAD

**Issue by m-worthen** [NetAppDocs/netapp-solutions#402]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_openshift.html

### Page title

OpenShift Overview

### Summary

I had to search outside the docset to find the definition of "ocp". Not a big deal however, if you aren't familiar with OpenShift and  acronyms used in the docset aren't defined, costs time to go find out what it means.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by banum-netapp** [comment]
pull request #444 has been created to address the issue. Once merged into the internal main, another pull request will be opened to merge with the main of the external facing documentation.

**Comment by kevin-hoke** [comment]
This has been addressed and is available in the latest version of the documentation.
