### ISSUE TITLE
second bullet point of pre-requisites not pointing to correct page.

### ISSUE THREAD

**Issue by harinaresh** [NetAppDocs/netapp-solutions#404]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp/gcp-setup.html

### Page title

Deploy and configure the Virtualization Environment on Google Cloud Platform (GCP)

### Summary

under pre-requisites, the second bullet point link (* Enable VMWare Engine API access and node quota) does not seem to be pointing to the correct link.
rather it is pointing to below link which talks about task_replication.
[Enable VMWare Engine API access and node quota](https://docs.netapp.com/us-en/occm/task_replicating_data.html)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
@sureshthoppay Can you please look into this?

**Comment by sureshthoppay** [comment]
I do see the updated link points to https://cloud.google.com/vmware-engine/docs/quickstart-prerequisites which is correct.
