### ISSUE TITLE
Configure SVMs for NVMe is a dead link in vSphere VMFS Datastore - NVMe/FC with ONTAP

### ISSUE THREAD

**Issue by leahynetapp** [NetAppDocs/netapp-solutions#406]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_auto_block_nvmeof.html

### Page title

vSphere VMFS Datastore - NVMe/FC with ONTAP

### Summary

Hyper link in documentation 
"a. Configure SVMs for NVMe." under ONTAP tasks step #2
[Configure SVMs for NVMe.](https://docs.netapp.com/us-en/netapp-solutions/virtualization/++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-CDDBD7F4-2089-4466-892F-F2DFF5798B1C.html)
Link gives "404 file not found"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
@leahynetapp - thank you for bringing this to our attention.  The link has been fixed and is available for your review in the initial URL.
