### ISSUE TITLE
Changes to Cloud Backup name

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/netapp-solutions#418]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/databases/snapctr_svcs_ora.html

### Page title

TR-4964: Oracle Database backup, restore and clone with SnapCenter Services

### Summary

There are two instances of "Cloud Backup" on this page. They should be changed as follows:

1. "Cloud Backup for Application" should be "BlueXP backup and recovery for applications"
2. "Cloud Backup documentation" should be "BlueXP backup and recovery documentation"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
Thank you for the feedback.  This has been fixed and available in the netapp-solutions repository.
