### ISSUE TITLE
Request to add note to "Use an IP hash teaming policy on ESXi"

### ISSUE THREAD

**Issue by chjones45** [NetAppDocs/netapp-solutions#426]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_best_practices.html

### Page title

Datastores and protocols

### Summary

This page lists "Use an IP hash teaming policy on ESXi" and also earlier includes "Disable LACP for switch ports connected to ESXi unless you are using dvSwitches 5.1 or later with LACP configured".

According to VMware KB 2006129 (https://kb.vmware.com/s/article/2006129), the use of the IP Hash teaming policy requires that LACP/EtherChannel is used on the ESXi hosts.

We have tested this today with a customer and found that using the IP Hash teaming policy without using LACP on the ESXi hosts results in degraded performance from the ESXi hosts accessing the ONTAP NFS Datastores.

Can I please request a note is added to the "Use an IP hash teaming policy on ESXi" statement that this only applies if using EtherChannel on the ESXi hosts, otherwise the default "Route based on the originating virtual port ID" policy should be used.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by chjones45** [comment]
Im going to close this. I guess it does actually say:

"NetApp recommends the following best practices for link aggregation:" as the start of the list of recommendations. So it does say this is for aggregation, so happy to say this isn't an issue and just me not reading carefully enough

**Comment by netapp-bingen** [comment]
Committed change to a new branch on the ontap-apps-dbs-internal. Closing this out.
