### ISSUE TITLE
template.adoc and samples.adoc are getting published

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/netapp-solutions#427]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/template.html

### Page title

`<Solution Name>`

### Summary

Also https://docs.netapp.com/us-en/netapp-solutions/samples.html

I suggest creating a branch in the dev repo with just `samples.adoc` and `template.adoc` and any other files you need for reference but don't want published. Name the branch something like `_reference-files-keep` for clarity and adjust your process docs to advise contributors to refer to it.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
Thank you for the feedback.  This has been fixed and available in the netapp-solutions repository.
