### ISSUE TITLE
Table is unreadable

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/netapp-solutions#431]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-support-configs.html

### Page title

Supported Configurations for NetApp Hybrid Multicloud with VMware

### Summary

The table on this page is scrambled and not readable:

![image](https://github.com/NetAppDocs/netapp-solutions/assets/43795/6a39d3bb-77bc-483c-bad6-2b0c006304fd)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
This has been fixed and is available at the reported link:

![image](https://github.com/NetAppDocs/netapp-solutions/assets/55808219/882eb2eb-87df-4c3b-bf98-4239b569feac)
