### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by preebeka** [NetAppDocs/netapp-solutions#439]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsrm-ontap9_new_features_with_srm_and_ontap_tools.html

### Page title

New features with SRM and ONTAP Tools

### Summary

This enables rapid resyncronization of mirrors at the exense of having to recalculate storage efficency savings post process.
**Please change exense to expense.**

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
Thank you for the feedback.  This has been fixed and available in the netapp-solutions repository.
