### ISSUE TITLE
Request for "airflow connections" settings on TR4798

### ISSUE THREAD

**Issue by sakaia** [NetAppDocs/netapp-solutions#44]
Request for TR4798

It is good to describe `airflow connections` on `custom-values.yaml` file.
Currently it is described WebUI only

Reference
-  [scheduler.connections@values.yaml](https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L231-L245)

**Comment by mboglesby** [comment]
My apologies for the late reply. Thanks for the feedback. We will consider adding this to our example custom-values.yaml next time that we refresh the solution.
