### ISSUE TITLE
Same Images?

### ISSUE THREAD

**Issue by preebeka** [NetAppDocs/netapp-solutions#442]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vvols-ontap.html

### Page title

Using vVols with ONTAP

### Summary

I see no difference between the images pasted under Example network configuration using vVols over NFS v3:
Both looks duplicate of each other.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
Thanks for the feedback.  This was a resolve merge conflicts issue where 2 instances of the image link were included after resolution.  It has been addressed.
