### ISSUE TITLE
Broken link in NetApp Capabilities for Google Cloud Platform GCVE

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/netapp-solutions#482]
### Summary

[https://docs.netapp.com/us-en/netapp-solutions/ehc/gcp/gcp-gcve.html#config](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fnetapp-solutions%2Fehc%2Fgcp%2Fgcp-gcve.html%23config&data=05%7C01%7CChanda.Jha%40netapp.com%7C49677a3226b24cdb524208dbf1e4d2bb%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638369737330167050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=04g3PGGSN3ixbybGvn74%2BTIwvG0J8nkUsUuIX27CGIQ%3D&reserved=0)
Please visit [Supported NetApp Storage Options](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fnetapp-solutions%2Fehc%2Fgcp%2Fehc-support-configs.html&data=05%7C01%7CChanda.Jha%40netapp.com%7C49677a3226b24cdb524208dbf1e4d2bb%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638369737330167050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AssGShSFwh5urTNuzSV8Z5mDAE%2FC1z4dbTWNR8QmWaU%3D&reserved=0) for more information.
The URL in that blurb in the doc link. Looks to be dead.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
This has been addressed and should be available now.
