### ISSUE TITLE
This doesn't list all the needed changes.

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/netapp-solutions#486]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_recommended_esxi_host_and_other_ontap_settings.html

### Page title

Recommended ESXi host and other ONTAP settings

### Summary

Hello. This doesn't have all the settings that need changed, compared to https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html#ats-locking. It would be good to have that updated or at least a reference to the other documentation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
Probably ideal to just remove the content and add a link to the HU page. That way we have a single source of truth.

I'll work on this next week.

**Comment by netapp-bingen** [comment]
This has been fixed in the next release. Additional settings added, as well as links to the other relevant docs added.
