### ISSUE TITLE
Need to add current ONTAP releases

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/netapp-solutions#487]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_and_vsphere_release-specific_information.html

### Page title

ONTAP and vSphere release-specific information

### Summary

You currently only show ONTAP releases up to ONTAP 9.8. Should this be updated to reflect ONTAP through ONTAP 9.14.1 (RC)?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
Honestly, I think in the next update I'll just be removing this page. I don't see it really adding any value. You could net the whole thing down to just "refer to the IMT and VCG". And we already say that elsewhere.

**Comment by netapp-bingen** [comment]
This page has been deprecated in the next release.
