### ISSUE TITLE
SCP screen images out of order

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/netapp-solutions#488]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vvols-deploy.html

### Page title

Deploying vVols Storage

### Summary

Please place the images (based on the bold "step" number on left side of each) in the correct order.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
This is fixed now in my branch. Will be published in the next major update.
