### ISSUE TITLE
Figures and Table References

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/netapp-solutions#489]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vvols-deploy.html

### Page title

Deploying vVols Storage

### Summary

Throughout the page, the text references different figures and tables by numbers, bu the figures and tables on the page have no corresponding numbers to use as references to align with the text.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
Fixed on this page.

**Comment by netapp-bingen** [comment]
These updates will be published in the next update.

**Comment by netapp-bingen** [comment]
Thanks for the feedback.
