### ISSUE TITLE
Video is not playable

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/netapp-solutions#519]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_demos_videos.html

### Page title

Virtualization Videos and Demos

### Summary

The video titled "ONTAP Tools for VMware - Overview" can't be played. It's asking me to sign in. This is most likely happening because Panopto videos must be in a public folder for embedding to work.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
The Panopto video ID is incorrect and I am currently building the repo with the correct ID.

**Comment by kevin-hoke** [comment]
This has been fixed.
