### ISSUE TITLE
Update cloud based managed Kubernetes recommendation

### ISSUE THREAD

**Issue by vrd83** [NetAppDocs/netapp-solutions#57]
NKS no longer exists. Do product management have a cloud-based recommendation to use instead, or do we want to remove mention of NKS?
Page: [Kubernetes Deployment](https://docs.netapp.com/us-en/netapp-solutions/ai/aicp_kubernetes_deployment.html)

**Comment by mboglesby** [comment]
@vrd83 - We are currently in the process refreshing the AI Control Plane documentation and will be updating this reference.

**Comment by mboglesby** [comment]
This was fixed by on May 18, 2021 - https://github.com/NetAppDocs/netapp-solutions/commit/f621beab561f1c9fd152b679adccee86ac8cca3b
