### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/netapp-solutions#571]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/ehc/bxp-scv-hybrid-solution.html

### Page title

3-2-1 Data Protection for VMware with SnapCenter Plug-in and BlueXP backup and recovery for VMs

### Summary

![image](https://github.com/NetAppDocs/netapp-solutions/assets/56453501/143c45eb-a3a2-49e0-ab0f-e695ddfde926)

```
. Once discovery is complete you will be able to view the datastores and virtual machines across all discovered SCV appliances.
 +
image::bxp-scv-hybrid-23.png[View available resources]
```

I came across this because of the space in front of the continuation marker (`+`) on the preceding line. The image file exists. The imagesdir notation is wrong, but other images on the page display, so that's not likely the problem. I suggest as the first step to remove the space before the continuation marker and see if that inexplicably fixes it. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by ntap-bmegan** [comment]
Oh wait, it's not that the image is missing, precisely, it's that it dumped the AsciiDoc notation. And since you have alt text, I misread the output initially. Definitely try the fix I suggested, and let me know the resolution.

**Comment by kevin-hoke** [comment]
Yes, that was the issue (space before the + sign) and I have it building as we speak.

**Comment by kevin-hoke** [comment]
This issue has been addressed in PR 583 and is available in the public repo.
