### ISSUE TITLE
se

### ISSUE THREAD

**Issue by adg331** [NetAppDocs/netapp-solutions#578]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/ai/aipod_nv_validation_sizing.html

### Page title

NetApp AIPod with NVIDIA DGX Systems - Solution Validation and Sizing Guidance

### Summary

There is a display issue in NetApp storage system sizing guidance, the sizing guide shows 'image::aipod_nv_sizing_new.png[]'

  

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
This has been addressed and available in the repository.
