### ISSUE TITLE
Missing Image on page

### ISSUE THREAD

**Issue by wolftales** [NetAppDocs/netapp-solutions#596]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/ai/aipod_nv_intro.html

### Page title

NetApp AIPod with NVIDIA DGX Systems - Introduction

### Summary

There appears to be a missing image on this page

```
NetApp AI Solutions Portfolio
image::aipod_nv_portfolio.png[]
```

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by ntapdave** [comment]
Issue corrected pending merge request approval.
