### ISSUE TITLE
Figure at bottom of page is broken

### ISSUE THREAD

**Issue by clubcaliche** [NetAppDocs/netapp-solutions#636]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/ai/aipod_nv_validation_sizing.html

### Page title

NVA-1173 NetApp AIPod with NVIDIA DGX Systems - Solution Validation and Sizing Guidance

### Summary

Figure showing input/output dialog or representing written content is missing.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kevin-hoke** [comment]
The image has been restored and is now available.
