### ISSUE TITLE
 NFS exports content type option is not visible in screenshot

### ISSUE THREAD

**Issue by toshiki-mukaeda** [NetAppDocs/netapp-solutions#663]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions/proxmox/proxmox-ontap.html

### Page title

Proxmox VE with ONTAP

### Summary

In NFS Storage, Virtualization Admin Tasks section 3,  
**Fill in the details, After providing the server info, the NFS exports should populate and pick from the list. Remember to select the content options.**
But screenshot's drop down menu shows Export, and content options is not visible. I think it should show content drop downs or specify in the document text like "Select Disk Image for nomal volumes".  
And cloud you add the information or explanation about all of supported content types supported by ONTAP ?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by sureshthoppay** [comment]
Thanks for the feedback. Will update the document with screenshot options for the content type. If not decided on specific content type, select all the content types for the NFS.
<img width="216" alt="image" src="https://github.com/user-attachments/assets/fbcc9735-0b79-44d5-849d-98d3dc7b9883">

**Comment by toshiki-mukaeda** [comment]
Thank you for quick response.   
How about "Preallocation"?   Which options are suitable for ONTAP?

**Comment by sureshthoppay** [comment]
We are capturing video and will soon add it to documentation. Default option (which is Metadata) provides better user experience. It is easy with ONTAP to expand the filesystem when required.
