### ISSUE TITLE
Bug in the link from Language Filter

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/netapp-solutions#69]
Page: [TR-4854: NetApp HCI for Citrix Virtual Apps and Desktops with Citrix Hypervisor](https://docs.netapp.com/us-en/netapp-solutions/vdi-vds/citrix_executive_summary.html)

I cannot see Japanese translation of this TR by selecting Japanese from the Language filter. Can you please fix it?

Thanks,
Yuka

**Comment by akseldavis** [comment]
Hi @yukakou, this issue should be corrected for all of NetApp Solutions. We would greatly appreciate your review and confirmation before closing the seven related issues. 

As always, thank you for helping us improve the quality of our technical content.

**Comment by yukakou** [comment]
Hi Aksel, thank you, but I see the translation of the top page still now when I select Japanese on the TR page.
![image](https://user-images.githubusercontent.com/50446078/118101174-454cbc80-b412-11eb-81a5-4ffc02643281.png)

**Comment by akseldavis** [comment]
Thank you, that helps clarify the original request. Yes, the language selector points to the root of each language site. I can open an internal enhancement request to have it point to the current page. I'm closing the related issues as the site is now resolving as designed.
